openapi: 3.0.0
info:
  title: Bucket.space
  description: Bucket.space is a content recommendation application, that allows users to post text content and get a feed of text content being recommended to them by the system.
  version: 1.0.0
servers:
  - url: http://localhost:2111/api/v1
    description: Main (production) server
  - url: http://localhost:2111
    description: Main Application URL